ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),

]

chat/urls.py
from django.contrib.auth.views import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('logout/', logout, {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['username','password1','password2']
        widgets = {
            'username': TextInput(attrs={'class':'form-control'}),
        }

chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message
from chat.forms import SignUpForm
from chat.serializers import MessageSerializer, UserSerializer


def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chats')



@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


def register_view(request):
    """
    Render registration template
    """
    if request.method == 'POST':
        print("working1")
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('chats')
    else:
        print("working2")
        form = SignUpForm()
    template = 'chat/register.html'
    context = {'form':form}
    return render(request, template, context)


def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/chat.html',
                      {'users': User.objects.exclude(username=request.user.username)})


def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, "chat/messages.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})

templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<div class="row">
    <nav class="blue lighten-3">
        <div class="nav-wrapper container">
            <div class="col s6">
                <a href="#" class="brand-logo" style="font-family: 'Pacifico', cursive;">Vibez</a>
            </div>
            <div class="col s6">
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="">{{ request.user.username }}</a></li>
                    <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
            <div class="card">
                <div class="collection">
                    {% for user in users %}
                    <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                        <img src="https://cdn4.iconfinder.com/data/icons/instagram-ui-twotone/48/Paul-18-512.png" class="col s2">
                        <div class="col s8">
                            <span class="title" style="font-weight: bolder">{{ user.username }}</span>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll; margin: auto;">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s10">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s2" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
    {% load staticfiles %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

templates/chat/index.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@100;300&family=Pacifico&display=swap" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class="container white-text center-align text">
            <h2 style="font-family: 'Pacifico', cursive;">vibez</h2>
            <p style="font-family: 'Archivo', sans-serif;">A Chatting App.</p>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3 style="font-family: 'Archivo', sans-serif;">
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 55%; position: relative; border-radius:10px;">
    <!--<div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>-->
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 55%; position: relative; border-radius:10px;">
    <!--<div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>-->
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3 style="font-family: 'Archivo', sans-serif;">
    Register
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Username</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Repeat Password</label>
                </div>
            </div>
            <div class="row">
                <div class="col s8">
                    <a href="{% url 'index' %}">already have an account ?</a>
                </div>
                <div class="col s4">
                <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Register</button>
                </div>
                </div>
            </div>
    </form>
{% endblock %}